### ISSUE TITLE
A script for inference singel image

### ISSUE THREAD

**Issue by Explore008** [qizhou000/tfman#1]
Good job! Can you offer a script to inference a singel image?I have tested sets5 daatasets by using the test.py,but produce a bad error...
![1712028169975](https://github.com/qizhou000/tfman/assets/111834651/f23f0bdd-0b0d-4443-b4ae-41a8b1a87cc2)
![1712028194414](https://github.com/qizhou000/tfman/assets/111834651/d6dc7993-c31a-436e-b648-601ececbbd75)

**Comment by qizhou000** [comment]
Thank you follow my repo! Please check if the HR folder exists.
